### ISSUE TITLE
cp .env.dist .env not doing anything

### ISSUE THREAD

**Issue by robertsmith7** [mikealmond/hq-trivia-assistant#4]
Displays nothing in terminal, and I've correctly followed all steps so far. There are no errors displayed either, so there might me something missing from my download.

**Comment by robertsmith7** [comment]
I caught myself and figured out it just needed a name. Is there anything specific I need to use or is info.env or something random like monkey.env ok?

**Comment by derka6391** [comment]
After trying to composer install i get error message:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - symfony/dom-crawler v4.0.3 requires php ^7.1.3 -> your PHP version (5.5.36) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.2 requires php ^7.1.3 -> your PHP version (5.5.36) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.1 requires php ^7.1.3 -> your PHP version (5.5.36) does not satisfy that requirement.
    - symfony/dom-crawler v4.0.0 requires php ^7.1.3 -> your PHP version (5.5.36) does not satisfy that requirement.
    - Installation request for symfony/dom-crawler ^4.0 -> satisfiable by symfony/dom-crawler[v4.0.0, v4.0.1, v4.0.2, v4.0.3].

**Comment by robertsmith7** [comment]
That has nothing to do with the issue listed above. There is a closed issue with the same issue that you're listing above. Learn how to use GitHub before asking useless questions @derka6391

**Comment by derka6391** [comment]
Mybad man, i am new to gethub. Where is the closed issue?

**Comment by robertsmith7** [comment]
https://github.com/mikealmond/hq-trivia-assistant/issues/1 and https://github.com/mikealmond/hq-trivia-assistant/issues/2. They'll both help in different ways but I'm not sure your issue was ever resolved.

**Comment by topper59** [comment]
@derka6391 Install php7.1-cli and php7.1-dom, you have 5.5. 

@robertsmith7 cp .env.dist .env should not display anything in terminal, as it just copies a file. After you copy it you can do nano .env or vi .env to edit the file and add your bearer and user ID.

A game does not have to be going on to get your info, you just start capturing packets and then open the HQ app, it will authenticate and pull your data. I don't have an iPhone and I didn't use Charles proxy, but you will have to do a MITM because the data is encrypted with SSL. This is much harder on Android 7+ because you must modify the APK to allow custom certs.
